/*
 * ETAPI
 *
 * External Trilium API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: zadam.apps@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppInfo {
    /// Trilium version
    #[serde(rename = "appVersion", skip_serializing_if = "Option::is_none")]
    pub app_version: Option<String>,
    /// DB version
    #[serde(rename = "dbVersion", skip_serializing_if = "Option::is_none")]
    pub db_version: Option<i32>,
    /// Sync protocol version
    #[serde(rename = "syncVersion", skip_serializing_if = "Option::is_none")]
    pub sync_version: Option<i32>,
    /// build date
    #[serde(rename = "buildDate", skip_serializing_if = "Option::is_none")]
    pub build_date: Option<String>,
    /// git build revision
    #[serde(rename = "buildRevision", skip_serializing_if = "Option::is_none")]
    pub build_revision: Option<String>,
    /// data directory where Trilium stores files
    #[serde(rename = "dataDirectory", skip_serializing_if = "Option::is_none")]
    pub data_directory: Option<String>,
    /// version of the supported Trilium Web Clipper protocol
    #[serde(rename = "clipperProtocolVersion", skip_serializing_if = "Option::is_none")]
    pub clipper_protocol_version: Option<String>,
    /// current UTC date time
    #[serde(rename = "utcDateTime", skip_serializing_if = "Option::is_none")]
    pub utc_date_time: Option<String>,
}

impl AppInfo {
    pub fn new() -> AppInfo {
        AppInfo {
            app_version: None,
            db_version: None,
            sync_version: None,
            build_date: None,
            build_revision: None,
            data_directory: None,
            clipper_protocol_version: None,
            utc_date_time: None,
        }
    }
}


