/*
 * ETAPI
 *
 * External Trilium API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: zadam.apps@gmail.com
 * Generated by: https://openapi-generator.tech
 */

/// Attribute : Attribute (Label, Relation) is a key-value record attached to a note.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Attribute {
    #[serde(rename = "attributeId", skip_serializing_if = "Option::is_none")]
    pub attribute_id: Option<String>,
    #[serde(rename = "noteId")]
    pub note_id: String,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<Type>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    #[serde(rename = "isInheritable", skip_serializing_if = "Option::is_none")]
    pub is_inheritable: Option<bool>,
    #[serde(rename = "utcDateModified", skip_serializing_if = "Option::is_none")]
    pub utc_date_modified: Option<String>,
}

impl Attribute {
    /// Attribute (Label, Relation) is a key-value record attached to a note.
    pub fn new(note_id: String) -> Attribute {
        Attribute {
            attribute_id: None,
            note_id,
            _type: None,
            name: None,
            value: None,
            position: None,
            is_inheritable: None,
            utc_date_modified: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "label")]
    Label,
    #[serde(rename = "relation")]
    Relation,
}

impl Default for Type {
    fn default() -> Type {
        Self::Label
    }
}

