/*
 * ETAPI
 *
 * External Trilium API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: zadam.apps@gmail.com
 * Generated by: https://openapi-generator.tech
 */

/// Branch : Branch places the note into the tree, it represents the relationship between a parent note and child note



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Branch {
    #[serde(rename = "branchId", skip_serializing_if = "Option::is_none")]
    pub branch_id: Option<String>,
    #[serde(rename = "noteId")]
    pub note_id: String,
    #[serde(rename = "parentNoteId")]
    pub parent_note_id: String,
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    #[serde(rename = "notePosition", skip_serializing_if = "Option::is_none")]
    pub note_position: Option<i32>,
    #[serde(rename = "isExpanded", skip_serializing_if = "Option::is_none")]
    pub is_expanded: Option<bool>,
    #[serde(rename = "utcDateModified", skip_serializing_if = "Option::is_none")]
    pub utc_date_modified: Option<String>,
}

impl Branch {
    /// Branch places the note into the tree, it represents the relationship between a parent note and child note
    pub fn new(note_id: String, parent_note_id: String) -> Branch {
        Branch {
            branch_id: None,
            note_id,
            parent_note_id,
            prefix: None,
            note_position: None,
            is_expanded: None,
            utc_date_modified: None,
        }
    }
}


