/*
 * ETAPI
 *
 * External Trilium API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: zadam.apps@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Error {
    /// HTTP status, identical to the one given in HTTP response
    #[serde(rename = "status")]
    pub status: i32,
    /// stable string constant
    #[serde(rename = "code")]
    pub code: String,
    /// Human readable error, potentially with more details,
    #[serde(rename = "message")]
    pub message: String,
}

impl Error {
    pub fn new(status: i32, code: String, message: String) -> Error {
        Error {
            status,
            code,
            message,
        }
    }
}


