/*
 * ETAPI
 *
 * External Trilium API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: zadam.apps@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SearchResponse {
    #[serde(rename = "results")]
    pub results: Vec<crate::models::Note>,
    /// debugging info on parsing the search query enabled with &debug=true parameter
    #[serde(rename = "debugInfo", skip_serializing_if = "Option::is_none")]
    pub debug_info: Option<serde_json::Value>,
}

impl SearchResponse {
    pub fn new(results: Vec<crate::models::Note>) -> SearchResponse {
        SearchResponse {
            results,
            debug_info: None,
        }
    }
}


